# taken from here https://en.wikipedia.org/wiki/List_of_pasta_dishes
vocab =
  c("'ncaciata", "'ncannulate", "'Ndruppeche", "'mbrusse", "acciughe",
  "aglio,", "agnello", "Agnolotti", "Alfredo", "all'ossolana",
  "all'aglione", "all'arrabbiata", "alla", "alle", "allo",
  "amari", "Amatriciana", "ampezzani", "Anelletti", "Anolini",
  "arriminati", "arselle", "Battolli", "bergamaschi", "Bigoli",
  "bisi", "bolognese", "Bolognese", "borragine", "briciole", "broccoli",
  "brodo", "Bucatini", "burro", "busa", "Busiate", "Caccavelle",
  "cace", "cacio", "Cacioricotta", "Caiegue", "campidanese", "Campofilone",
  "Canederli", "Cannelloni", "Cappellacci", "Cappelletti", "capra",
  "Capresi", "Capunsei", "Caramelle", "carbonara", "Carpenedolo",
  "carrettiera", "Casoncelli", "Castel", "castelmagno", "Casunziei",
  "Cavatelli", "Cavati", "ceci", "Ceppe", "chitarra", "Chnefflene",
  "Cicatelli", "cicciari", "Ciceri", "cime", "cinghiale", "cinta",
  "Cjarsons", "Cocule", "Colorno", "Corzetti", "cremaschi", "cremonesi",
  "Culurgiones", "cutteure", "d'Ogliastra", "d'oca", "della",
  "Dols", "fagioli", "faso", "ferraresi", "Ferretti", "Fettuccine",
  "Fileja", "fonduta", "forno", "Fregola", "frutti", "funghi",
  "Garganelli", "Gnocchi", "Goffredo", "Gramigna", "Gricia", "Insalata",
  "l'anatra", "Lagane", "Laina", "Lasagne", "Lorighittas", "lucchesi",
  "Macarones", "Maccaronara", "Maccaruni", "Maccheroncini", "Maccheroni",
  "Mafalde", "Malfatti", "malga", "Malloreddus", "Maltagliati",
  "mantovani", "mare", "maremmani", "Marubini", "Mincio", "mollica",
  "mollicata", "Mpurnatu", "musso", "napoletano", "nduja", "nero",
  "Nidi", "noci", "norcina", "Norma", "nunnata", "olio", "Orecchiette",
  "Pajata", "Palina", "Pallotte", "Pansoti", "papavero", "Pappardelle",
  "Passatelli", "pasta", "Pasta", "pastora", "patate", "pavesi",
  "Penne", "pepe", "peperoncino", "pesto", "pesto)", "Pici", "piemontesi",
  "pinoli", "Pisarei", "piselli", "pistacchio", "Pizzoccheri",
  "Plin", "pollo", "pomodori", "Portofino", "Possenta", "prosciutto",
  "puntarelle,", "puttanesca", "radicchio", "ragu", "ragusana",
  "rapa", "Ravioli", "ricci", "ricotta", "ricotta,", "Rigatoni",
  "romana", "rondine", "rosso", "Sagne", "salentine", "salsa",
  "salsiccia", "salvia", "sarde", "Scarpinocc", "Scarpolesi", "Scialatielli",
  "scoglio", "Scrippelle", "secchi,", "senese", "seppia", "sguasarot",
  "silana", "sorrentina", "Spaghetti", "Spatzle", "speck", "spinaci",
  "Strangozzi", "Stroncatura", "Strozzapreti", "sugo", "Tagliatelle",
  "Tagliolini", "tartufo", "Testaroli", "Timballo", "Tordelli",
  "Tortel", "Tortelli", "Tortellini", "Tortelloni", "trapanese",
  "Trenette", "Tria", "trippa", "Troccoli", "Trofie", "Turtel",
  "Valeggio", "Valtellina", "verdi", "vesuviana", "Vincisgrassi",
  "vongole", "Walser", "zafferano", "Ziti", "zucca")
